apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: openai-modelconfig
  namespace: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-4.1-mini
  provider: OpenAI